# Generated by Django 4.2.22 on 2025-06-09 17:25

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0114_computedfield_grouping'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPSModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(default='Unknown Location', max_length=200)),
                ('capacity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('manufacturer', models.CharField(default='Unknown Manufacturer', max_length=100)),
                ('model_number', models.CharField(default='Unknown Model Number', max_length=100)),
                ('serial_number', models.CharField(default='Unknown Serial Number', max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=100, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('last_test_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'UPS Model',
                'verbose_name_plural': 'UPS Model',
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
