# Generated by Django 4.2.22 on 2025-06-06 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_app_power_plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upsmodel',
            name='capacity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='upsmodel',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upsmodel',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upsmodel',
            name='last_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upsmodel',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=200),
        ),
        migrations.AddField(
            model_name='upsmodel',
            name='manufacturer',
            field=models.CharField(default='Unknown Manufacturer', max_length=100),
        ),
        migrations.AddField(
            model_name='upsmodel',
            name='model_number',
            field=models.CharField(default='Unknown Model Number', max_length=100),
        ),
        migrations.AddField(
            model_name='upsmodel',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='upsmodel',
            name='serial_number',
            field=models.CharField(default='Unknown Serial Number', max_length=100),
        ),
        migrations.AddField(
            model_name='upsmodel',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
