# Generated by Django 4.2.22 on 2025-06-09 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0062_module_data_migration'),
        ('nautobot_app_power_plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upsmodel',
            name='power_panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ups_models', to='dcim.powerpanel'),
        ),
    ]
